# Generated by Django 6.0.5 on 2026-06-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='dni_o_rut',
            new_name='cedula',
        ),
    ]
