# Generated by Django 6.0.6 on 2026-06-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicina', models.CharField(max_length=100)),
                ('precio_medicina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_medicina', models.IntegerField()),
                ('estado_medicina', models.CharField(default='Disponible', max_length=20)),
            ],
        ),
    ]
