# Generated by Django 6.0.5 on 2026-06-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('medicinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('indicaciones', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citas.cita')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleResultadoMedicina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('dosis', models.CharField(max_length=255)),
                ('medicina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicinas.medicina')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_medicamentos', to='resultados.resultado')),
            ],
        ),
    ]
